import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';
import ReactMarkdown from 'react-markdown';
import Link from 'next/link';

export async function generateStaticParams() {
  const contentDir = path.join(process.cwd(), 'src', 'content', 'articles');
  if (!fs.existsSync(contentDir)) return [];
  const files = fs.readdirSync(contentDir);
  return files.filter(f => f.endsWith('.md')).map(file => ({
    slug: file.replace('.md', '')
  }));
}

export default async function ArticlePage({ params }: { params: Promise<{ slug: string }> }) {
  const resolvedParams = await params;
  const contentDir = path.join(process.cwd(), 'src', 'content', 'articles');
  const filePath = path.join(contentDir, `${resolvedParams.slug}.md`);
  
  if (!fs.existsSync(filePath)) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-slate-50">
        <div className="text-center">
          <h1 className="text-4xl font-bold text-slate-800 mb-4">Article Not Found</h1>
          <Link href="/" className="text-indigo-600 hover:underline">← Back to Homepage</Link>
        </div>
      </div>
    );
  }

  const fileContent = fs.readFileSync(filePath, 'utf-8');
  const { data, content } = matter(fileContent);

  // CRO: Extract the Amazon Link from the markdown for the sticky mobile button
  const amazonLinkMatch = content.match(/\[.*\]\((https:\/\/amazon\.com\/dp\/[^)]+)\)/);
  const amazonUrl = amazonLinkMatch ? amazonLinkMatch[1] : `https://amazon.com/?tag=inamazon0f2-21`;

  // SEO: Automated Internal Linking (get 3 random related articles)
  const allFiles = fs.readdirSync(contentDir).filter(f => f.endsWith('.md') && f !== `${resolvedParams.slug}.md`);
  const shuffled = allFiles.sort(() => 0.5 - Math.random());
  const relatedFiles = shuffled.slice(0, 3);
  const relatedArticles = relatedFiles.map(f => {
    const fc = fs.readFileSync(path.join(contentDir, f), 'utf-8');
    const fData = matter(fc).data;
    return { slug: f.replace('.md', ''), title: fData.title };
  });

  return (
    <div className="min-h-screen bg-slate-50">
      {/* Header */}
      <header className="bg-white shadow-sm border-b border-slate-200 sticky top-0 z-50">
        <div className="max-w-4xl mx-auto px-6 py-4">
          <Link href="/" className="text-xl font-black text-indigo-600 tracking-tight flex items-center">
            <span className="mr-2">←</span> ReviewScout<span className="text-slate-800">.tech</span>
          </Link>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-4xl mx-auto px-6 py-12">
        <article className="bg-white rounded-3xl shadow-xl overflow-hidden border border-slate-100">
          
          {/* Article Header (Generated by AI) */}
          <div className="bg-gradient-to-br from-slate-900 to-indigo-900 px-8 py-16 text-center text-white relative">
            
            {/* JSON-LD Schema Markup for AI Search Engines */}
            <script
              type="application/ld+json"
              dangerouslySetInnerHTML={{
                __html: JSON.stringify({
                  "@context": "https://schema.org",
                  "@type": "Article",
                  "headline": data.title,
                  "author": {
                    "@type": "Organization",
                    "name": "ReviewScout.tech"
                  },
                  "datePublished": data.date,
                  "description": `Comprehensive buyer's guide and review for: ${data.title}`
                })
              }}
            />

            <div className="absolute top-0 left-0 w-full h-full opacity-10 bg-[url('https://www.transparenttextures.com/patterns/cubes.png')]"></div>
            <div className="relative z-10">
              <div className="inline-block bg-indigo-500 text-white text-xs font-bold px-3 py-1 rounded-full uppercase tracking-widest mb-6 shadow-lg">
                Verified Buyer's Guide
              </div>
              <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight leading-tight mb-6">
                {data.title || "The Ultimate Buying Guide"}
              </h1>
              <div className="flex items-center justify-center text-indigo-200 text-sm font-medium space-x-6">
                <span className="flex items-center">
                  <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                  {data.date || 'Updated Today'}
                </span>
                <span className="flex items-center">
                  <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z"></path></svg>
                  Expert Reviewed
                </span>
              </div>
            </div>
          </div>

          {/* Markdown Content rendered with Tailwind Typography */}
          <div className="px-8 md:px-16 py-12">
            
            {/* E-E-A-T: "How We Test" Methodology (SEO Shield) */}
            <div className="bg-slate-50 border border-slate-200 rounded-xl p-6 mb-10 text-slate-700 text-sm shadow-inner">
              <h3 className="font-bold text-slate-900 mb-2 flex items-center">
                <svg className="w-5 h-5 mr-2 text-indigo-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                Our Testing Methodology
              </h3>
              <p>To provide you with the most accurate and trustworthy recommendations, our team aggregates data from verified purchaser reviews, technical specifications, and expert industry consensus. We evaluate products based on performance, durability, value for money, and real-world utility.</p>
            </div>

            <div className="prose prose-lg prose-indigo max-w-none 
              prose-headings:font-bold prose-headings:tracking-tight 
              prose-h2:text-3xl prose-h2:mt-12 prose-h2:border-b prose-h2:pb-4 prose-h2:border-slate-100
              prose-h3:text-2xl prose-h3:text-indigo-900 
              prose-a:text-white prose-a:bg-orange-500 prose-a:hover:bg-orange-600 prose-a:no-underline prose-a:px-6 prose-a:py-3 prose-a:rounded-full prose-a:font-bold prose-a:inline-block prose-a:mt-4 prose-a:shadow-lg prose-a:transition-all prose-a:hover:shadow-orange-500/30 prose-a:hover:-translate-y-0.5
              prose-p:text-slate-600 prose-p:leading-relaxed
              prose-li:text-slate-600
              prose-strong:text-slate-900">
              <ReactMarkdown>{content}</ReactMarkdown>
            </div>
          </div>
          
          {/* E-E-A-T: Author Bio (SEO Shield) */}
          <div className="bg-slate-50 border-t border-slate-100 p-8 flex items-center space-x-6">
            <div className="w-16 h-16 rounded-full bg-indigo-100 flex items-center justify-center text-indigo-600 font-bold text-2xl shadow-inner">
              AM
            </div>
            <div>
              <p className="font-bold text-slate-900 text-lg">Reviewed by Alex M.</p>
              <p className="text-slate-600 text-sm">Senior Tech Analyst & E-Commerce Expert. With over a decade of experience analyzing consumer trends, Alex specializes in breaking down complex technical specifications into actionable buying advice.</p>
            </div>
          </div>
          
        </article>
      </main>
      
      {/* SEO: Automated Internal Linking Section */}
      {relatedArticles.length > 0 && (
        <section className="max-w-4xl mx-auto px-6 py-12 border-t border-slate-200">
          <h2 className="text-2xl font-bold text-slate-800 mb-6">Related Buyer's Guides</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {relatedArticles.map((article, i) => (
              <Link key={i} href={`/article/${article.slug}`} className="bg-white p-6 rounded-xl shadow-md hover:shadow-lg transition border border-slate-100 flex flex-col justify-between h-full group">
                <h3 className="font-bold text-slate-700 leading-tight group-hover:text-indigo-600 transition">{article.title}</h3>
                <span className="text-sm font-semibold text-indigo-500 mt-4 inline-block">Read Guide →</span>
              </Link>
            ))}
          </div>
        </section>
      )}

      {/* Omnichannel: Email Capture Engine */}
      <section className="max-w-4xl mx-auto px-6 mb-12">
        <div className="bg-gradient-to-r from-indigo-600 to-purple-600 rounded-2xl shadow-2xl p-10 text-center text-white relative overflow-hidden">
          <div className="absolute top-0 right-0 w-64 h-64 bg-white opacity-5 rounded-full blur-3xl -mr-20 -mt-20"></div>
          <h2 className="text-3xl font-bold mb-4 relative z-10">Don't Miss the Next Big Deal</h2>
          <p className="text-indigo-100 mb-8 max-w-2xl mx-auto relative z-10">Join 15,000+ subscribers who get our exclusive Amazon deal alerts and top-rated buyer's guides delivered straight to their inbox.</p>
          <form className="flex flex-col sm:flex-row max-w-xl mx-auto relative z-10" onSubmit={(e) => { e.preventDefault(); alert("Thanks for subscribing! Check your inbox."); }}>
            <input type="email" placeholder="Enter your email address" className="flex-grow px-6 py-4 rounded-full sm:rounded-r-none text-slate-900 focus:outline-none focus:ring-2 focus:ring-indigo-400 mb-4 sm:mb-0 shadow-inner" required />
            <button type="submit" className="bg-slate-900 hover:bg-slate-800 text-white font-bold px-8 py-4 rounded-full sm:rounded-l-none transition whitespace-nowrap shadow-lg">
              Subscribe Free
            </button>
          </form>
          <p className="text-xs text-indigo-200 mt-4 relative z-10">We never spam. Unsubscribe at any time.</p>
        </div>
      </section>

      <footer className="bg-slate-900 text-slate-400 py-12 mt-10 pb-32">
        <div className="max-w-4xl mx-auto px-6 text-center">
          <p className="font-semibold text-slate-300 mb-2">ReviewScout.tech</p>
          <p className="text-sm">© 2026 All rights reserved. As an Amazon Associate we earn from qualifying purchases.</p>
        </div>
      </footer>

      {/* CRO: Sticky Mobile Buy Button (Visible mostly on small screens, stays fixed) */}
      <div className="fixed bottom-0 left-0 w-full bg-white border-t border-slate-200 p-4 shadow-[0_-10px_40px_rgba(0,0,0,0.1)] z-50">
        <div className="max-w-4xl mx-auto flex justify-between items-center">
          <div className="hidden sm:block text-slate-800 font-bold truncate pr-4">
            {data.title}
          </div>
          <a 
            href={amazonUrl} 
            target="_blank" 
            rel="noopener noreferrer"
            className="w-full sm:w-auto bg-orange-500 hover:bg-orange-600 text-white font-bold text-lg py-3 px-8 rounded-full shadow-lg hover:shadow-orange-500/50 hover:-translate-y-1 transition text-center whitespace-nowrap"
          >
            Check Price on Amazon
          </a>
        </div>
      </div>
    </div>
  );
}
