import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';
import ReactMarkdown from 'react-markdown';
import Link from 'next/link';

export async function generateStaticParams() {
  const contentDir = path.join(process.cwd(), 'src', 'content', 'articles');
  if (!fs.existsSync(contentDir)) return [];
  const files = fs.readdirSync(contentDir);
  return files.filter(f => f.endsWith('.md')).map(file => ({
    slug: file.replace('.md', '')
  }));
}

export default async function ArticlePage({ params }: { params: Promise<{ slug: string }> }) {
  const resolvedParams = await params;
  const contentDir = path.join(process.cwd(), 'src', 'content', 'articles');
  const filePath = path.join(contentDir, `${resolvedParams.slug}.md`);
  
  if (!fs.existsSync(filePath)) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-slate-50">
        <div className="text-center">
          <h1 className="text-4xl font-bold text-slate-800 mb-4">Article Not Found</h1>
          <Link href="/" className="text-indigo-600 hover:underline">← Back to Homepage</Link>
        </div>
      </div>
    );
  }

  const fileContent = fs.readFileSync(filePath, 'utf-8');
  const { data, content } = matter(fileContent);

  return (
    <div className="min-h-screen bg-slate-50">
      {/* Header */}
      <header className="bg-white shadow-sm border-b border-slate-200 sticky top-0 z-50">
        <div className="max-w-4xl mx-auto px-6 py-4">
          <Link href="/" className="text-xl font-black text-indigo-600 tracking-tight flex items-center">
            <span className="mr-2">←</span> ReviewScout<span className="text-slate-800">.tech</span>
          </Link>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-4xl mx-auto px-6 py-12">
        <article className="bg-white rounded-3xl shadow-xl overflow-hidden border border-slate-100">
          
          {/* Article Header (Generated by AI) */}
          <div className="bg-gradient-to-br from-slate-900 to-indigo-900 px-8 py-16 text-center text-white relative">
            <div className="absolute top-0 left-0 w-full h-full opacity-10 bg-[url('https://www.transparenttextures.com/patterns/cubes.png')]"></div>
            <div className="relative z-10">
              <div className="inline-block bg-indigo-500 text-white text-xs font-bold px-3 py-1 rounded-full uppercase tracking-widest mb-6 shadow-lg">
                Verified Buyer's Guide
              </div>
              <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight leading-tight mb-6">
                {data.title || "The Ultimate Buying Guide"}
              </h1>
              <div className="flex items-center justify-center text-indigo-200 text-sm font-medium space-x-6">
                <span className="flex items-center">
                  <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                  {data.date || 'Updated Today'}
                </span>
                <span className="flex items-center">
                  <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z"></path></svg>
                  Expert Reviewed
                </span>
              </div>
            </div>
          </div>

          {/* Markdown Content rendered with Tailwind Typography */}
          <div className="px-8 md:px-16 py-12">
            <div className="prose prose-lg prose-indigo max-w-none 
              prose-headings:font-bold prose-headings:tracking-tight 
              prose-h2:text-3xl prose-h2:mt-12 prose-h2:border-b prose-h2:pb-4 prose-h2:border-slate-100
              prose-h3:text-2xl prose-h3:text-indigo-900 
              prose-a:text-white prose-a:bg-orange-500 prose-a:hover:bg-orange-600 prose-a:no-underline prose-a:px-6 prose-a:py-3 prose-a:rounded-full prose-a:font-bold prose-a:inline-block prose-a:mt-4 prose-a:shadow-lg prose-a:transition-all prose-a:hover:shadow-orange-500/30 prose-a:hover:-translate-y-0.5
              prose-p:text-slate-600 prose-p:leading-relaxed
              prose-li:text-slate-600
              prose-strong:text-slate-900">
              <ReactMarkdown>{content}</ReactMarkdown>
            </div>
          </div>
          
        </article>
      </main>
      
      <footer className="bg-slate-900 text-slate-400 py-12 mt-20">
        <div className="max-w-4xl mx-auto px-6 text-center">
          <p className="font-semibold text-slate-300 mb-2">ReviewScout.tech</p>
          <p className="text-sm">© 2026 All rights reserved. As an Amazon Associate we earn from qualifying purchases.</p>
        </div>
      </footer>
    </div>
  );
}
