export function processAutoLinks(content: string, productName: string): string {
  if (!content) return content;
  
  let newContent = content;

  const skimlinksId = "307054X1795329";

  const affiliateIds = {
    awin: "3003527",
    shareasale: "3003527",
    digistore24: "adminai091181b6",
    earnkaro: "5476200",
    amazon: "inamazon0f2-21"
  };

  const encodedProduct = encodeURIComponent(productName || "best products");

  // 1. Process explicit Markdown Links generated by AI with placeholder IDs
  // This intercepts [Text](url) and rewrites the URL to our Geo-Router proxy with real IDs
  newContent = newContent.replace(/\[([^\]]+)\]\((https?:\/\/[^\)]+)\)/gi, (match, text, url) => {
    let finalUrl = url;
    
    if (url.includes('amazon.')) {
      finalUrl = `/api/go?url=${encodeURIComponent(`https://www.amazon.com/s?k=${encodedProduct}&tag=${affiliateIds.amazon}`)}`;
    } else if (url.includes('aliexpress.com')) {
      finalUrl = `/api/go?url=${encodeURIComponent(`https://go.redirectingat.com/?id=${skimlinksId}&url=${encodeURIComponent(`https://www.aliexpress.com/wholesale?SearchText=${encodedProduct}`)}`)}`;
    } else if (url.includes('ebay.com')) {
      // eBay via Skimlinks
      finalUrl = `/api/go?url=${encodeURIComponent(`https://go.redirectingat.com/?id=${skimlinksId}&url=${encodeURIComponent(`https://www.ebay.com/sch/i.html?_nkw=${encodedProduct}`)}`)}`;
    } else if (url.includes('awin1.com')) {
      // Awin -> Etsy Universal Search (Etsy Merchant ID: 6220)
      finalUrl = `/api/go?url=${encodeURIComponent(`https://www.awin1.com/cread.php?awinmid=6220&awinaffid=${affiliateIds.awin}&clickref=&p=${encodeURIComponent(`https://www.etsy.com/search?q=${encodedProduct}`)}`)}`;
    } else if (url.includes('shareasale.com')) {
      // ShareASale -> DHgate Wholesale Search (Merchant 42409)
      finalUrl = `/api/go?url=${encodeURIComponent(`https://www.shareasale.com/r.cfm?b=1639527&u=${affiliateIds.shareasale}&m=42409&urllink=${encodeURIComponent(`https://www.dhgate.com/wholesale/search.do?searchkey=${encodedProduct}`)}`)}`;
    } else if (url.includes('walmart.com')) {
      // Walmart via Skimlinks
      finalUrl = `/api/go?url=${encodeURIComponent(`https://go.redirectingat.com/?id=${skimlinksId}&url=${encodeURIComponent(`https://www.walmart.com/search?q=${encodedProduct}`)}`)}`;
    } else if (url.includes('bestbuy.com')) {
      // BestBuy via Skimlinks
      finalUrl = `/api/go?url=${encodeURIComponent(`https://go.redirectingat.com/?id=${skimlinksId}&url=${encodeURIComponent(`https://www.bestbuy.com/site/searchpage.jsp?st=${encodedProduct}`)}`)}`;
    } else if (url.includes('flipkart.com')) {
      // Flipkart Universal Search (via EarnKaro)
      finalUrl = `/api/go?url=${encodeURIComponent(`https://www.flipkart.com/search?q=${encodedProduct}&affid=ekaro_${affiliateIds.earnkaro}`)}`;
    } else if (url.includes('croma.com')) {
      // Croma Universal Search (via EarnKaro)
      finalUrl = `/api/go?url=${encodeURIComponent(`https://www.croma.com/searchB?q=${encodedProduct}&affid=ekaro_${affiliateIds.earnkaro}`)}`;
    } else if (url.includes('digistore24.com')) {
      // Digistore24 -> Tube Mastery (High Converting Digital AI/Tech Course - ID 299134)
      finalUrl = `/api/go?url=${encodeURIComponent(`https://www.digistore24.com/redir/299134/${affiliateIds.digistore24}/REVIEW`)}`;
    }
    
    return `[${text}](${finalUrl})`;
  });

  // 2. Auto-link specific keywords in plain text (excluding already linked text)
  const keywords = [
    "Amazon", 
    "Check Price", 
    "Buy now", 
    "Best price", 
    "Available here",
    "Click here",
    "View on Amazon",
    "Check it out"
  ];

  const rawAmzUrl = `https://www.amazon.com/s?k=${encodedProduct}&tag=${affiliateIds.amazon}`;
  const cloakedAmzUrl = `/api/go?url=${encodeURIComponent(rawAmzUrl)}`;

  // Use a single, lightning-fast O(n) regex to match either an existing markdown link OR a keyword.
  // This completely eliminates the ReDoS timeout (5xx Server Error) caused by unbounded lookbehinds in V8.
  const kwPattern = keywords.map(kw => `\\b${kw}\\b`).join('|');
  const regex = new RegExp(`(\\[.*?\\]\\(.*?\\))|(${kwPattern})`, 'gi');

  newContent = newContent.replace(regex, (match, existingLink, keyword) => {
    if (existingLink) {
      return existingLink; // Don't modify existing markdown links
    } else if (keyword) {
      return `[${keyword}](${cloakedAmzUrl})`; // Convert plain keywords into links
    }
    return match;
  });

  return newContent;
}
