export function processAutoLinks(content: string, productName: string): string {
  if (!content) return content;
  
  let newContent = content;

  const affiliateIds = {
    aliexpress: "reviewscout_ai",
    shareasale: "3003527",
    awin: "3003527",
    digistore24: "adminai091181b6",
    amazon: "inamazon0f2-21"
  };

  const encodedProduct = encodeURIComponent(productName || "best products");

  // 1. Process explicit Markdown Links generated by AI with placeholder IDs
  // This intercepts [Text](url) and rewrites the URL to our Geo-Router proxy with real IDs
  newContent = newContent.replace(/\[([^\]]+)\]\((https?:\/\/[^\)]+)\)/gi, (match, text, url) => {
    let finalUrl = url;
    
    if (url.includes('amazon.')) {
      finalUrl = `/api/go?url=${encodeURIComponent(`https://www.amazon.com/s?k=${encodedProduct}&tag=${affiliateIds.amazon}`)}`;
    } else if (url.includes('aliexpress.com')) {
      finalUrl = `/api/go?url=${encodeURIComponent(`https://www.aliexpress.com/wholesale?SearchText=${encodedProduct}&aff_id=${affiliateIds.aliexpress}`)}`;
    } else if (url.includes('awin1.com') || url.includes('shareasale.com')) {
      finalUrl = `/api/go?url=${encodeURIComponent(`https://www.awin1.com/cread.php?awinmid=12345&awinaffid=${affiliateIds.awin}&clickref=&p=`)}`;
    } else if (url.includes('digistore24.com')) {
      finalUrl = `/api/go?url=${encodeURIComponent(`https://www.digistore24.com/redir/12345/${affiliateIds.digistore24}/CAMPAIGNKEY`)}`;
    }
    
    return `[${text}](${finalUrl})`;
  });

  // 2. Auto-link specific keywords in plain text (excluding already linked text)
  const keywords = [
    "Amazon", 
    "Check Price", 
    "Buy now", 
    "Best price", 
    "Available here",
    "Click here",
    "View on Amazon",
    "Check it out"
  ];

  const rawAmzUrl = `https://www.amazon.com/s?k=${encodedProduct}&tag=${affiliateIds.amazon}`;
  const cloakedAmzUrl = `/api/go?url=${encodeURIComponent(rawAmzUrl)}`;

  keywords.forEach(kw => {
    const regex = new RegExp(`(?<!\\[[^\\]]*)(?<!\\([^\\]]*)\\b(${kw})\\b(?![^\\[]*\\])(?![^\\(]*\\))`, 'gi');
    newContent = newContent.replace(regex, `[$1](${cloakedAmzUrl})`);
  });

  return newContent;
}
